name: Bun CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install
            - run: DW_KEY=${{ secrets.DW_KEY }} GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }} GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }} bun run test-bun
