name: Bun CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: touch .env && echo DW_KEY='{{ secrets.DW_KEY }}' >> .env && echo GOOGLE_SERVICE_ACCOUNT_EMAIL='{{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}' >> .env && echo GOOGLE_PRIVATE_KEY='{{ secrets.GOOGLE_PRIVATE_KEY }}' >> .env && cat .env
            - run: bun install
            - run: bun run test-bun
